//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDeTiempo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        public int IdAnuncio { get; set; }
        public int Categoria { get; set; }
        public int Usuario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Demanda Demanda { get; set; }
        public virtual Oferta Oferta { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
